# nginx-deployment.yaml
apiVersion: apps/v1 #specify api version
kind: Deployment #resource type
metadata: #contains name of deployment
  name: nginx-deployment
spec: #defines state of deploment
  replicas: 3 #number of pods created
  selector:
    matchLabels:
      app: nginx
  template: #describe the pods that should be created
    metadata:
      labels: 
        app: nginx
    spec:
      containers: #list of containers
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80 #port at which it is getting mapped
